version: "3.9"
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: "tasker"
      POSTGRES_USER: "postgresql"
      POSTGRES_PASSWORD: "postgresql"
    ports:
      - "5432:5432"